### PR TITLE
Update jenkins-notifier.coffee

### PR DESCRIPTION
**Pull request by JasonSmiley**

### CODE REVIEW

**Comment by JasonSmiley** [comment]
This is ready for review, but I haven't added the sound clips to BigBoard yet.

Not sure why here is a merge conflict.

**Comment by cmckendry** [comment]
It looks like you just missed @andromedado migrating this script from Coffescript to pure Javascript, which may be why this commit won't merge cleanly.

Can you revise this to make the same change to new-jenkins-notifier.js instead of jenkins-notifier.coffee?

**Comment by JasonSmiley** [comment]
I'll look into this later today - Thanks carter

**Comment by andromedado** [comment]
I'll take care of it

**Comment by andromedado** [comment]
merged manually

**Pull request merged**
