### PR TITLE
Panda bomb

### PR DESCRIPTION
**Pull request by prestifidibs**

### CODE REVIEW

**Comment by andromedado** [comment]
:+1:

**Comment by andromedado** [comment]
you just have to add it to the `src/index.js`

**Comment by andromedado** [comment]
Also, unless it was an explicit choice, add documentation so that it's visible in dibsy help

e.g.
https://github.com/1stdibs/hubot-scripts/blob/master/src/scripts/shiabomb.js#L1

**Comment by prestifidibs** [comment]
added docs, and updated index.js

**Comment by andromedado** [comment]
:fireworks:  :panda_face:  :fireworks:  :panda_face: :fireworks:

**Pull request merged**
