### PR TITLE
i think these regexes are a thing...

### PR DESCRIPTION
**Pull request by TBragg**

### CODE REVIEW

**Comment by lilianammmatos** [comment]
I'm not sure I want to say goodbye to `dibsy slame`...

**Comment by cmckendry** [comment]
@lilianammmatos I feel the dibsy same

**Comment by lilianammmatos** [comment]
slam

**Comment by TBragg** [comment]
You may feel the same, just as long as you don't feel the slame

**Comment by lilianammmatos** [comment]
@TBragg, how about you make it more interesting...? :smirk: :smirk: :smirk: Change it so that as long as `dibsy` and `slam` are in the message, in that order, you should get slammed e.g.:

```
dibsy that was a good slame
dibsy, how about you hit me with that slam?
dibsy i swear to god if you don't slam rn
```

Happy regex-ing! 

... and use this site to test: https://regex101.com/

**Comment by cmckendry** [comment]
We could even support `dibsy salami`

**Comment by lilianammmatos** [comment]
The possibilities are endless...

**Comment by andromedado** [comment]
`/.*s.*l.*a.*m.*/`  ^_^

**Comment by TBragg** [comment]
you fools

/dibsy.*sa?lami?/gi

spider-man_this_isn t_even_my_final_form

**Pull request closed without merging**
